# Configuración para usar Base de Datos H2 en memoria dentro de Render
spring.datasource.url=jdbc:h2:mem:cinescape;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto permite que Hibernate cree tus tablas automáticamente basadas en tus Entidades/Modelos
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true